duneopdet/OpticalDetector/opticaldetectorservices_dune.fcl
This PR contains changes related to the photonbacktrackerservice. Following the geant4 refactoring, and the update of the PhotonBacktrackerService in https://github.com/LArSoft/larsim/pull/93 to accommodate for that change.
Some cleaning of similar tables.
=> Update PhotonBacktracker Service definitions

duneopdet/OpticalDetector/SIPMOpSensorSim.fcl
Parameters according to ProtoDUNE-DP.
=> Updating doped Ar with 10ppm Xe params

duneopdet/OpticalDetector/OpFlashFinderDualPhase_module.cc, duneopdet/PhotonPropagation/PhotonVisibilityServiceS2_service.cc
Pursuant to LArSoft/larcorealg#33
=> Accommodate breaking changes in geometry

duneopdet/OpticalDetector/OpFlashFinderDualPhase_module.cc, duneopdet/PhotonPropagation/PhotonVisibilityServiceS2_service.cc
=> Revert "Accommodate breaking changes in geometry"

duneopdet/OpticalDetector/OpFlashFinderDualPhase_module.cc, duneopdet/PhotonPropagation/PhotonVisibilityServiceS2_service.cc
Pursuant to LArSoft/larcorealg#33
=> Accommodate geometry interface changes (redo)

duneopdet/PhotonPropagation/ScintTimeTools/ScintTimeXeDoping.h, duneopdet/PhotonPropagation/ScintTimeTools/ScintTimeXeDoping_tool.cc
The two methods work as intended but I'm not using them because they're not efficient.
Accompanying PR to https://github.com/LArSoft/larsim/pull/111
=> Define fastScintTime() and slowScintTime() to satisfy parent class requirement

duneopdet/OpticalDetector/SIPMOpSensorSim_module.cc, duneopdet/OpticalDetector/WaveformDigitizerSim_module.cc, duneopdet/PhotonPropagation/PhotonLibraryPropagationS2_module.cc
=> Changes for art 3.12

duneopdet/PhotonPropagation/PDFastSim_dune.fcl
In `PDFastSim_dune.fcl`, I added codes to apply computational graph model for protoDUNE_VD PDS, the graph model is based on protodunevd_v2_refactored.gdml
=> Computational graph codes for protoDUNE_vd PDS

duneopdet/OpticalDetector/OpHitFinder/OpHitFinderDeco_module.cc
Deprecated terminal output was printed at the end of the script. Indenting has been changed to make the module more readable. There are 2 options InputDigiType = recob/raw. The main option of interest for the updated PDS workflow is 'recob'. The 'raw' option is to be used for legacy wvfs coming directly from the digitizer stage (without deconvolution).
=> REMOVE OBSOLETE COUT AND REFORMAT CONTENT

duneopdet/OpticalDetector/CMakeLists.txt, duneopdet/OpticalDetector/SolarOpFlash.fcl, duneopdet/OpticalDetector/SolarOpFlash_module.cc
Trying to make the solar analysis more modular. Start with a producer for solar flash (work in progress).
=> FIRST UPLOAD SOLAR FLASH PRODUCER

duneopdet/OpticalDetector/SolarOpFlash_module.cc
Include small changes and improvements to print info during solar reco workflow.
=> Solar duneopdet

duneopdet/OpticalDetector/SolarOpFlash_module.cc
The time adjacency parameter has been made asymmetric to match the scintillation profile better.
=> UPDATE SOLARFLASH FOR NEW FCL CONFIG AND ALGORITHM PARAMETERS

duneopdet/OpticalDetector/Deconvolution/DecoAnalysis_module.cc, duneopdet/OpticalDetector/OpDetDigitizerProtoDUNEHD_module.cc
- Overflow fix on ProtoDUNEHD detsim.
- Update DecoAnalysis to avoid copying too much.
=> Two bug fix

duneopdet/OpticalDetector/Deconvolution/Deconvolution.fcl, duneopdet/OpticalDetector/Deconvolution/dune_opdet_channels.fcl, duneopdet/OpticalDetector/opticaldetectormodules_dune.fcl
Fixing mis-configuration for PDHD MC deconvolution. Need to change the search path for the template files.
=> Update to fix Deconvolution.fcl

duneopdet/OpticalDetector/SolarOpFlash.fcl, duneopdet/SolarNuUtils/AdjOpHitsUtils.cc, duneopdet/SolarNuUtils/AdjOpHitsUtils.h, duneopdet/SolarNuUtils/SolarAuxUtils.cc
Providing a specific flash reconstruction for the different PDS planes in VD and solving a segfault bug in the OpHit clustering algorithm.
=> mantheys opflash optimization for VD and bug fix

duneopdet/OpticalDetector/OpFlashFinderVerticalDrift.fcl, duneopdet/OpticalDetector/OpFlashFinderVerticalDrift_module.cc
I slightly modified the VD flash finder to deal with non-consecutive channels.
The critical change is in line 264.
Please, let me know if you validate the change for the Far Detector, otherwise I will duplicate the module for PDVD.
=> VD Flash Finder update to deal with PDVD channel map

duneopdet/OpticalDetector/opticaldetectormodules_dune.fcl
Setup the default PDVD PDS modules for the decoding and reconstruction
=> Add PDVD PDS reco chain

duneopdet/OpticalDetector/CMakeLists.txt, duneopdet/OpticalDetector/OpDetDigitizerProtoDUNEVD_module.cc, duneopdet/OpticalDetector/opticaldetectormodules_dune.fcl
New digitizer that deals with PMTs/Xarapucas, with Ar and Xe light.
=> New PDVD digitizer

duneopdet/PhotonPropagation/PDFastSim_dune.fcl
This PR is based on another PR in larsimdnn: https://github.com/LArSoft/larsimdnn/pull/14;
Moreover, only when the comp graph module files are put in stashcache, will this module finally work.
=> Add comp graph module for full-size FD1

duneopdet/OpticalDetector/opticaldetectormodules_dune.fcl
Hi @lpaulucc, 
I’ve updated the ChannelMap configuration for the ProtoDUNE-VD detsim stage.  
This aligns the simulation with the new mapping file (`PDVD_PDS_Mapping_v07082025.json`).  
Could you please review?
=> Update ChannelMap for PDVD detsim stage
